[meta]
name     = "TM Agent"
author   = "XertroV"
category = "Agent"
version  = "0.2.0"

[script]
#__DEFINES__
dependencies = ["mcp-tm", "ai-api", "MLHook"]
export_dependencies = ["MLHook"]

module = "Agent"
timeout = 60000
